name: Run Go Logging benchmarks
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true

      - name: Install the latest versions of each library
        run: go get -u ./... && go mod tidy

      - name: Install gobenchdata
        run: go install go.bobheadxi.dev/gobenchdata@latest

      - name: Benchmark Go Logging Libraries
        run: go test -bench . -benchmem ./... | gobenchdata --json bench.json

      - name: Commit benchmark results to repo
        uses: EndBug/add-and-commit@v9
        with:
          message: Update benchmark results
          commit: '--no-verify'
